export const QUIZ_CATEGORIES = [
  'Animals',
  'Art',
  'Artificial Intelligence',
  'Astronomy',
  'Biology',
  'Blockchain',
  'Business',
  'Chemistry',
  'Comics',
  'Culture',
  'Current Affairs',
  'Education',
  'Engineering',
  'Environment',
  'Fashion',
  'Food',
  'General Knowledge',
  'Geography',
  'Health',
  'History',
  'IoT',
  'Languages',
  'Literature',
  'Mathematics',
  'Movies',
  'Music',
  'Physics',
  'Politics',
  'Programming',
  'Robotics',
  'Science',
  'Space',
  'Sports',
  'Startups',
  'Technology',
  'Travel',
  'Video Games',
];
